affer/urls.py
from django.urls import path
from .views import *
from .import views

app_name = "affer"


urlpatterns = [
    path('taga/',  views.tags_list, name="tags_list_url"),
    path('taga/<str:slug>/', views.tags_detail, name="tags_detail_url"),
    path('tags/', views.tags_list, name="tags_list_url"),
    path('tag/create', TagCreate.as_view(), name="tag_create_url"),


]

arts/urls.py
from django.urls import path
from .import views
from django.conf.urls import url

app_name = 'arts'

urlpatterns = [
    path('', views.home, name='home'),
    url('rocket', views.minimale),
    url(r'^(?P<slug>[\w-]+)/landscapes$', views.detailus, name='detailus'), 
    url(r'^(?P<slug>[\w-]+)/minimalism$', views.details, name='details' ),
    url('abstraction', views.abstraction),
    url(r'^abs(?P<slug>[\w-]+)/$', views.detailsabs, name='detailsabs'),
    url('landscapes', views.landscapes, name="landscapes"),

    path('offer', views.offer, name='offer'),
]

pictures/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings
from django.conf.urls import url

urlpatterns = [
    path('admin/', admin.site.urls),
    path('home/', include('arts.urls')),
    path('where/', include('where.urls')),
    url(r'^accounts/', include('accounts.urls')),
    path('affer/', include('affer.urls'))
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

affer/models.py
from django.db import models

# Create your models here.
class Tag(models.Model):
    title = models.CharField(max_length=50)
    slug = models.SlugField(max_length=50, unique=True)
    thumb = models.ImageField(default='default.png', blank=True, upload_to='media')

    def __str__(self):
        return self.title

affer/forms.py
from django import forms
from .models import Tag
from django.core.exceptions import ValidationError


class TagForm(forms.Form):
    title  = forms.CharField(max_length=50)
    slug = forms.CharField(max_length=50)
    thumb = forms.ImageField()


    def clean_slug(self):
        new_slug = self.cleaned_data['slug'].lower()

        if new_slug == 'create':
            raise ValidationError('Slug may not be "Create"')
        if Tag.objects.filter(slug__iexact=new_slug).count():
            raise ValidationError('Slug must be unique. We have "{}" slug already'.format(new_slug))
        return new_slug

    def save(self):
        new_tag = Tag.objects.create(
            title=self.cleaned_data['title'],
            slug=self.cleaned_data['slug'],
            thumb=self.cleaned_data['thumb']

        )
        return new_tag

affer/views.py
from django.shortcuts import render
from django.shortcuts import redirect
from django.shortcuts import get_object_or_404
from django.views.generic import View
from .models import  Tag
from .forms import TagForm



def tags_list(request):
    tags = Tag.objects.all()
    return render(request, 'affer/tags_list.html', context={'tags':tags})



def tags_detail(request, slug):
    tag = Tag.objects.get(slug__iexact=slug)
    return render(request, 'affer/tags_detail.html', context={'tag':tag})


#class TagDetail( View):
    #def get(self, request, slug):
        #tag = Tag.objects.get(slug__iexact=slug2)
        #tag = get_object_or_404(Tag, slug__iexact=slug)
        #return render(request, 'affer/tags_detail.html', context={'tag':tag})




class TagCreate(View):
    def get(self, request):
        form = TagForm()
        return render(request, 'affer/tags_create.html', context={'form':form})

    def post(self, request):
        bound_form = TagForm(request.POST, request.FILES)

        if bound_form.is_valid():
            new_tag = bound_form.save()
            return redirect('arts:home')
        return render(request, 'affer/tags_create.html', context={'form':bound_form})

affer/templates/affer/tags_create.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <div class="">
      <form class="" enctype="multipart/form-data" action="{% url 'affer:tag_create_url' %}" method="post">
        {% csrf_token %}
          {{ form.title }}
          {{ form.slug }}
          {{ form.thumb }}

        <button type="submit" class="btn btn-primary">Create Tag</button>
      </form>
    </div>
  </body>
</html>

affer/templates/affer/tags_detail.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <div class="">
        <h1 class="mt-5">Post with  "{{ tag.title|title }}" tag:</h1>
        <img src="{{ tag.thumb.url }}" />

    </div>
  </body>
</html>

affer/templates/affer/tags_list.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <div class="">
      <h1 class="mb-5">Tags:</h1>
      {% for tag in tags %}
        <h3><a href="{% url 'affer:tags_detail_url' slug=tag.slug %}" >{{ tag.title }}</a></h3>
      {% endfor %}
    </div>
  </body>
</html>