accounts/urls.py
from django.urls import path
from .import views
from django.conf.urls import url

app_name = 'accounts'

urlpatterns = [
    url(r'^signup/$', views.signup_view, name="signup"),
    url(r'^login/$', views.login_view, name="login"),
]

affer/urls.py
from django.urls import path
from .views import *
from .import views

app_name = "affer"


urlpatterns = [
    path('taga/',  views.tags_list, name="tags_list_url"),
    path('taga/<str:slug>/', views.tags_detail, name="tags_detail_url"),
    path('tags/', views.tags_list, name="tags_list_url"),
    path('tag/create', TagCreate.as_view(), name="tag_create_url"),


]

arts/urls.py
from django.urls import path
from .import views
from django.conf.urls import url

app_name = 'arts'

urlpatterns = [
    path('', views.home, name='home'),
    url('rocket', views.minimale),
    url(r'^(?P<slug>[\w-]+)/landscapes$', views.detailus, name='detailus'), 
    url(r'^(?P<slug>[\w-]+)/minimalism$', views.details, name='details' ),
    url('abstraction', views.abstraction),
    url(r'^abs(?P<slug>[\w-]+)/$', views.detailsabs, name='detailsabs'),
    url('landscapes', views.landscapes, name="landscapes"),

    path('offer', views.offer, name='offer'),
]

pictures/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings
from django.conf.urls import url

urlpatterns = [
    path('admin/', admin.site.urls),
    path('home/', include('arts.urls')),
    path('where/', include('where.urls')),
    url(r'^accounts/', include('accounts.urls')),
    path('affer/', include('affer.urls'))
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

where/urls.py
from django.urls import path
from .import views
from django.conf.urls import url



app_name = 'where'

urlpatterns = [
    path('offers', views.offers, name="offers"),
    url('games', views.game, name="game"),
    url(r'^games(?P<slug>[\w-]+)/$', views.detailgame, name='detailgame' ),
    url('films', views.film, name="film"),
    url(r'^(?P<slug2>[\w-]+)/film$', views.detailfilms, name='detailfilms' ),


]

arts/models.py
from django.db import models

# Create your models here.
class Minimalism(models.Model):
    title = models.CharField(max_length=100)
    slug = models.SlugField()
    thumb  = models.ImageField(default='default.png', blank=True)

    def __str__(self):
        return self.title



class Abstraction(models.Model):
    title = models.CharField(max_length=100)
    slug = models.SlugField()
    thumb  = models.ImageField(default='default.png', blank=True)

    def __str__(self):
        return self.title


class Landscapes(models.Model):
    title = models.CharField(max_length=100)
    slug = models.SlugField()
    thumb  = models.ImageField(default='default.png', blank=True)

    def __str__(self):
        return self.title

arts/views.py
from django.shortcuts import render, redirect
from .models import Minimalism, Abstraction, Landscapes
import random

def offer(request):
    return render(request, 'arts/offer.html')

def home(request):
    return render(request, 'arts/home.html')


def minimale(request):
    minss = Minimalism.objects.count()
    mins = Minimalism.objects.all()
    random_mins = random.sample(list(mins), minss)
    return render(request, 'arts/minimalism.html', {'random_mins':random_mins})


def details(request, slug):

    minimalism = Minimalism.objects.get(slug=slug)
    return render(request, 'arts/details.html', {'minimalism':minimalism})


def detailus(request, slug):
    landscapes = Landscapes.objects.get(slug=slug)
    return render(request, 'arts/landdet.html', {'landscapes':landscapes})


def abstraction(request):
    abstractionss = Abstraction.objects.count()
    abstractions = Abstraction.objects.all()
    random_abstractions = random.sample(list(abstractions), abstractionss)
    return render(request, 'arts/abstraction.html', {'random_abstractions':random_abstractions})


def detailsabs(request, slug):
    abstraction = Abstraction.objects.get(slug=slug)
    return render(request, 'arts/detailabs.html', {'abstraction':abstraction})

def landscapes(request):
    landscapesss = Landscapes.objects.count()
    landscapess = Landscapes.objects.all()
    random_landscapess = random.sample(list(landscapess), landscapesss)
    return render(request, 'arts/landscapes.html', {'random_landscapess':random_landscapess})

arts/templates/arts/abstraction.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <link rel="stylesheet" href="/static/stylemin.css">
  </head>
  <body>
    <h2>hddh</h2>
    <div class="abs">
      <h2>fuck</h2>
      {% for abstraction in random_abstractions %}
        <div class="abstr">
          <a href="{% url 'arts:detailsabs' slug=abstraction.slug %}"><img src="{{ abstraction.thumb.url }}"/></a>

        </div>
      {% endfor %}
  </body>
</html>

arts/templates/arts/detailabs.html
{% load static %}
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <link rel="stylesheet" href="/static/styledet.css">
  </head>
  <body>
    <form class="" action="index.html" method="post">

    </form>

    <div class="header">
      <h2 class="name">{{ abstraction.title }}</h2>
      <a class="download" download href="{{ abstraction.thumb.url }}">Download Picture</a><br>
      <a class="homep" href="{% url 'arts:home' %}">Home Page</a><br>
    </div>




      <div class="content">
        <img src="{{ abstraction.thumb.url }}" />

      </div>




  </body>
</html>

arts/templates/arts/details.html
{% load static %}
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <link rel="stylesheet" href="/static/styledet.css">
  </head>
  <body>
    <form class="" action="index.html" method="post">

    </form>

    <div class="header">
      <h2 class="name">{{ minimalism.title }}</h2>
      <a class="download" download href="{{ minimalism.thumb.url }}">Download Picture</a><br>
      <a class="homep" href="{% url 'arts:home' %}">Home Page</a><br>
    </div>




      <div class="content">
        <img src="{{ minimalism.thumb.url }}" />

      </div>




  </body>
</html>

arts/templates/arts/home.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <link rel="stylesheet" href="/static/styles.css">

  </head>
  <body>
    <div class="header">

        <h2><a href="rocket">Minimalism</a></h2>
        <h2><a href="abstraction">Abstraction</a></h2>
        <h2><a href="{% url 'arts:landscapes'%}">Landscapes</a></h2>
        <h2><a href="{% url 'where:game' %}">From Games</a></h2>
        <h2><a href="{% url 'where:film' %}">From Films</a></h2>

        <h2 class="rock"><a href="{% url 'accounts:signup' %}">Зарегестироваться</a></h2>
        <h2 class="duck"><a href="{% url 'accounts:login' %}">Войти</a></h2>
    </div>
    <div class="down">
      <em class="offer"><a href="{% url 'affer:tag_create_url' %}">Offer picture</a></em>
    </div>
    <div class="basement">
      <a href="https://vk.com/public195225601">Наш ВК</a>
    </div>

  </body>
</html>

arts/templates/arts/landdet.html
{% load static %}
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <link rel="stylesheet" href="/static/styledet.css">
  </head>
  <body>
    <form class="" action="index.html" method="post">

    </form>

    <div class="header">
      <h2 class="name">{{ landscapes.title }}</h2>
      <a class="download" download href="{{ landscapes.thumb.url }}">Download Picture</a><br>
      <a class="homep" href="{% url 'arts:home' %}">Home Page</a><br>
    </div>




      <div class="content">
        <img src="{{ landscapes.thumb.url }}" />

      </div>




  </body>
</html>

arts/templates/arts/landscapes.html
{% load static %}
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <link rel="stylesheet" href="/static/stylemin.css">
  </head>
  <body>
    <h2>fuck</h2>
    <div class="mar">
      <h2>fuck</h2>
      {% for landscapes in random_landscapess %}
        <div class="">
          <a href="{% url 'arts:detailus' slug=landscapes.slug %}"><img src="{{ landscapes.thumb.url }}"/></a>

        </div>
      {% endfor %}
      <div class="right">
        <h2>jaja</h2>

      </div>
    </div>


  </body>
</html>

arts/templates/arts/minimalism.html
{% load static %}
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <link rel="stylesheet" href="/static/stylemin.css">
  </head>
  <body>
    <h2>fuck</h2>
    <div class="mar">
      <h2>fuck</h2>
      {% for minimalism in random_mins %}
        <div class="">
          <a href="{% url 'arts:details' slug=minimalism.slug %}"><img src="{{ minimalism.thumb.url }}"/></a>

        </div>
      {% endfor %}
      <div class="right">
        <h2>jaja</h2>

      </div>
    </div>


  </body>
</html>