arts/urls.py
from django.urls import path
from .import views
from django.conf.urls import url

app_name = 'arts'

urlpatterns = [
    path('', views.home, name='home'),
    url('rocket', views.minimale),
    url(r'^(?P<slug>[\w-]+)/landscapes$', views.detailus, name='detailus'), 
    url(r'^(?P<slug>[\w-]+)/minimalism$', views.details, name='details' ),
    url('abstraction', views.abstraction),
    url(r'^abs(?P<slug>[\w-]+)/$', views.detailsabs, name='detailsabs'),
    url('landscapes', views.landscapes, name="landscapes"),

    path('offer', views.offer, name='offer'),
]

pictures/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings
from django.conf.urls import url

urlpatterns = [
    path('admin/', admin.site.urls),
    path('home/', include('arts.urls')),
    path('where/', include('where.urls')),
    url(r'^accounts/', include('accounts.urls')),
    path('affer/', include('affer.urls'))
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

where/urls.py
from django.urls import path
from .import views
from django.conf.urls import url



app_name = 'where'

urlpatterns = [
    path('offers', views.offers, name="offers"),
    url('games', views.game, name="game"),
    url(r'^games(?P<slug>[\w-]+)/$', views.detailgame, name='detailgame' ),
    url('films', views.film, name="film"),
    url(r'^(?P<slug2>[\w-]+)/film$', views.detailfilms, name='detailfilms' ),


]

where/models.py
from django.db import models

# Create your models here.
class Games(models.Model):
    title = models.CharField(max_length=100)
    slug = models.SlugField()
    thumb  = models.ImageField(default='default.png', blank=True)

    def __str__(self):
        return self.title


class Films(models.Model):
    title = models.CharField(max_length=100)
    slug = models.SlugField()
    thumb  = models.ImageField(default='default.png', blank=True)

    def __str__(self):
        return self.title




class Offer(models.Model):
    title = models.CharField(max_length=100)
    slug = models.SlugField()
    thumb  = models.ImageField(default='default.png', blank=True)

    def __str__(self):
        return self.title

where/views.py
from django.shortcuts import render
from .models import Games, Films
import random



def offers(request):
    return render(request, 'where/offers.html')

def game(request):
    gamesss = Games.objects.count()
    gamess = Games.objects.all()
    random_gamess = random.sample(list(gamess), gamesss)
    return render(request, 'where/game.html', {'random_gamess':random_gamess})


def detailgame(request, slug):
    games = Games.objects.get(slug=slug)
    return render(request, 'where/gamedet.html', {'games':games})


def film(request):
    filmsss = Films.objects.count()
    filmss = Films.objects.all()
    random_gamess = random.sample(list(filmss), filmsss)
    return render(request, 'where/film.html', {'random_gamess':random_gamess})


def detailfilms(request, slug2):
    films = Films.objects.get(slug=slug2)
    return render(request, 'where/filmdet.html', {'films':films})

where/templates/where/film.html
{% load static %}
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <link rel="stylesheet" href="/static/stylemin.css">
  </head>
  <body>
    <h2>fuck</h2>
    <div class="mar">
      <h2>fuck</h2>
      <h1>aatmosfera</h1>
      {% for films in random_gamess %}
        <div class="">
          <a href="{% url 'where:detailfilms' slug2=films.slug %}"><img src="{{ films.thumb.url }}"/></a>

        </div>
      {% endfor %}
      <div class="right">
        <h2>jaja</h2>

      </div>
    </div>


  </body>
</html>

where/templates/where/filmdet.html
{% load static %}
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <link rel="stylesheet" href="/static/styledet.css">
  </head>
  <body>

    <div class="header">
      <h2 class="name">{{ films.title }}</h2>
      <a class="download" download href="{{ films.thumb.url }}">Download Picture</a><br>
      <a class="homep" href="{% url 'arts:home' %}">Home Page</a><br>
    </div>
    <div class="content">
      <img src="{{ films.thumb.url }}" />
    </div>

    <h2>dd</h2>

  </body>
</html>

where/templates/where/game.html
{% load static %}
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <link rel="stylesheet" href="/static/stylemin.css">
  </head>
  <body>
    <h2>fuck</h2>
    <div class="mar">
      <h2>fuck</h2>
      <h1>aatmosfera</h1>
      {% for games in random_gamess %}
        <div class="">
          <a href="{% url 'where:detailgame' slug=games.slug %}"><img src="{{ games.thumb.url }}"/></a>

        </div>
      {% endfor %}
      <div class="right">
        <h2>jaja</h2>

      </div>
    </div>


  </body>
</html>

where/templates/where/gamedet.html
{% load static %}
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <link rel="stylesheet" href="/static/styledet.css">
  </head>
  <body>
    <form class="" action="index.html" method="post">

    </form>

    <div class="header">
      <h2 class="name">{{ games.title }}</h2>
      <a class="download" download href="{{ games.thumb.url }}">Download Picture</a><br>
      <a class="homep" href="{% url 'arts:home' %}">Home Page</a><br>
    </div>




      <div class="content">
        <img src="{{ games.thumb.url }}" />

      </div>




  </body>
</html>

where/templates/where/offers.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <input type="text" name="" value="">
  </body>
</html>